# Generated by Django 3.2.6 on 2021-10-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
